# Stage 1: Build Flutter app
FROM ghcr.io/cirruslabs/flutter:3.22.0-alpine AS builder

WORKDIR /app

COPY flutter_app ./
RUN flutter config --no-analytics && \
    flutter pub get && \
    flutter build web --release

# Stage 2: Serve with Nginx
FROM nginx:alpine

COPY --from=builder /app/build/web /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
